import copy
import numpy as np
from collections import defaultdict
import random as random
import matplotlib.pyplot as plt
from pathlib import Path
import random

def ev_monte_carlo(env, pi, gamma, s0, n_samples=200, T=100, V_true = None):
    """
    Estimate the state-value function V^π using every-visit Monte Carlo
    policy evaluation.

    Episodes are generated by following policy π in the environment.
    For each visit of a state within a trajectory, the discounted return
    from that time step onward is computed and used to update the state's
    value estimate via an incremental running average.

    Parameters
    ----------
    env : Environment
        Environment with transition dynamics and reward function.

    pi : dict
        Policy where `pi[s][a]` gives the probability of taking action `a`
        in state `s`.

    gamma : float
        Discount factor applied to future rewards.

    s0 : state or None
        Initial state for each episode. If `None`, episodes start from
        a randomly chosen state.

    n_samples : int, optional
        Number of Monte Carlo episodes to sample.

    T : int, optional
        Maximum trajectory length per episode.

    V_true : dict, optional
        Reference value function used to track convergence error.

    Returns
    -------
    V : dict
        Estimated state-value function.

    dist : np.ndarray or None
        Per-episode error relative to `V_true`, if provided.
    """
    # Value estimate for each state (running average form)
    V = defaultdict(float)

    # Count of how many times each state has been visited
    N = defaultdict(int)
    

    # Optional tracking of L1 error vs true value function
    if V_true is None:
        dist = None
    else:
        dist = np.zeros(n_samples)

    # Loop over Monte Carlo episodes
    for i in range(n_samples):
        
        # Generate an episode following policy pi
        state = s0 if s0 is not None else random.choice(list(env.states()))
        trajectory = []
        for t in range(T):
            if state == env.battery_pos:
                break
            
            action = random.choices(range(env.num_actions), weights=pi[state])[0]
            next_state = env.step(state, action)
            reward = env.reward(next_state, state, action)
            trajectory.append((state, action, reward))
            state = next_state

        # Update value estimates using every-visit returns
        G = 0
        for t in reversed(range(len(trajectory))):
            s_t, a_t, r_t = trajectory[t]
            G = gamma * G + r_t
            N[s_t] += 1
            V[s_t] = (V[s_t]*(N[s_t]-1) + G) / N[s_t]
        
        # Optional diagnostics
        if V_true is not None:
            dist[i] = max(np.abs(V[s] - V_true[s]) for s in env.states())   

    # print(f"Final L1 error: {dist[-1] if dist is not None else 'N/A'}")
    return V, dist

def fv_monte_carlo(env, pi, gamma, s0, n_samples=200, T=100, V_true = None):
    """
    Estimate the state-value function V^π using first-visit Monte Carlo
    policy evaluation.

    Episodes are generated by following policy π in the environment.
    For each state, only the first occurrence within an episode is used
    to compute a discounted return and update the state's value estimate
    via an incremental running average.

    Parameters
    ----------
    env : Environment
        Environment with transition dynamics and reward function.

    pi : dict
        Policy where `pi[s][a]` gives the probability of taking action `a`
        in state `s`.

    gamma : float
        Discount factor applied to future rewards.

    s0 : state or None
        Initial state for each episode. If `None`, episodes start from
        a randomly chosen state.

    n_samples : int, optional
        Number of Monte Carlo episodes to sample.

    T : int, optional
        Maximum trajectory length per episode.

    V_true : dict, optional
        Reference value function used to track convergence error.

    Returns
    -------
    V : dict
        Estimated state-value function.

    dist : np.ndarray or None
        Per-episode error relative to `V_true`, if provided.
    """
    # Value estimate for each state (running average form)
    V = defaultdict(float)

    # Count of how many times each state has been visited
    N = defaultdict(int)

    # Optional tracking of L1 error vs true value function
    if V_true is None:
        dist = None
    else:
        dist = np.zeros(n_samples)

    # Loop over Monte Carlo episodes
    for i in range(n_samples):
        
        # Generate an episode following policy pi
        state = s0 if s0 is not None else random.choice(list(env.states()))
        trajectory = []
        for t in range(T):
            if state == env.battery_pos:
                break
                
            action = random.choices(range(env.num_actions), weights=pi[state])[0]
            next_state = env.step(state, action)
            reward = env.reward(next_state, state, action)
            trajectory.append((state, action, reward))
            state = next_state

        # Update value estimates using first-visit returns
        G = 0
        for t in reversed(range(len(trajectory))):
            s_t, a_t, r_t = trajectory[t]
            G = gamma * G + r_t
            if np.all([s_t != s for s, a, r in trajectory[:t]]):  # Check if this is the first visit
                N[s_t] += 1
                # Inkrementeller Durchschnitt über alle Episoden
                V[s_t] = (V[s_t] * (N[s_t] - 1) + G) / N[s_t]
        
        # Optional diagnostics
        if V_true is not None:
            dist[i] = max(np.abs(V[s] - V_true[s]) for s in env.states())

    # print(f"Final L1 error: {dist[-1] if dist is not None else 'N/A'}")

    return V, dist